import { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import typedocSidebar from "./docs/api/typedoc-sidebar";

const sidebars: SidebarsConfig = {
	sidebar: [
		"introduction", // 👈 remove or replace this
		// {
		// 	type: "category",
		// 	label: "Guide",
		// 	items: [{ type: "autogenerated", dirName: "guide" }],
		// },
		{
			type: "category",
			label: "API Reference",
			link: { type: "doc", id: "api/index" },
			items: typedocSidebar.items,
		},
	],
};

export default sidebars;
