import { $ } from "bun";

const OWNER = "louiszn";
const REPO = "bakit";

const BASE_BRANCH = "main";
const RELEASE_BRANCH = "changeset-release/main";

const API_URL = `https://codeberg.org/api/v1/repos/${OWNER}/${REPO}`;

interface PullRequest {
	number: number;
	head?: {
		ref?: string;
	};
	base?: {
		ref?: string;
	};
}

function resolveEnv(name: string): string {
	const value = process.env[name];

	if (!value) {
		throw new Error(`Missing environment variable: ${name}`);
	}

	return value;
}

async function configureGit(): Promise<void> {
	console.log("[git] Configuring Git");

	await $`git config user.name "Bakit CI"`;
	await $`git config user.email "git@louiszn.fyi"`;

	await $`git config --unset-all http.sslCAInfo`.nothrow().quiet();
}

async function configureRemote(): Promise<void> {
	const token = resolveEnv("CODEBERG_TOKEN");
	const url = `https://${token}@codeberg.org/${OWNER}/${REPO}.git`;
	await $`git remote set-url origin ${url}`;
}

async function hasStagedChanges(): Promise<boolean> {
	const result = await $`git diff --cached --quiet`.nothrow().quiet();

	switch (result.exitCode) {
		case 0:
			return false;

		case 1:
			return true;

		default:
			throw new Error(`git diff failed with exit code ${result.exitCode}`);
	}
}

async function codebergRequest<T>(path: string, init?: RequestInit): Promise<T> {
	const token = resolveEnv("CODEBERG_TOKEN");

	const response = await fetch(`${API_URL}${path}`, {
		...init,
		headers: {
			Authorization: `token ${token}`,
			"Content-Type": "application/json",
			...init?.headers,
		},
	});

	if (!response.ok) {
		const body = await response.text();

		throw new Error(
			`Codeberg API request failed: ${response.status} ${response.statusText}\n${body}`,
		);
	}

	return (await response.json()) as T;
}

async function ensureReleasePullRequest(): Promise<void> {
	console.log("[pr] Checking for existing release PR");

	const pullRequests = await codebergRequest<PullRequest[]>("/pulls?state=open&limit=50");

	const existing = pullRequests.find(
		(pr) => pr.head?.ref === RELEASE_BRANCH && pr.base?.ref === BASE_BRANCH,
	);

	if (existing) {
		console.log(`[pr] Release PR #${existing.number} already exists`);

		return;
	}

	console.log("[pr] Creating release PR");

	const created = await codebergRequest<PullRequest>("/pulls", {
		method: "POST",
		body: JSON.stringify({
			base: BASE_BRANCH,
			head: RELEASE_BRANCH,
			title: "chore: version packages",
			body: "This PR was automatically generated by Changesets.",
		}),
	});

	console.log(`[pr] Release PR #${created.number} created`);
}

async function main(): Promise<void> {
	resolveEnv("CODEBERG_TOKEN");

	await configureGit();

	console.log("[release] Creating release branch");
	await $`git checkout -B ${RELEASE_BRANCH}`;

	console.log("[changesets] Versioning packages");
	await $`bunx changeset version`;

	console.log("[deps] Updating lockfile");
	await $`bun install`;

	console.log("[git] Staging changes");
	await $`git add .`;

	if (!(await hasStagedChanges())) {
		throw new Error("changeset version produced no changes");
	}

	console.log("[git] Creating version commit");
	await $`git commit -m ${"chore: version packages"}`;
	await configureRemote();

	console.log("[git] Pushing release branch");
	await $`git push --force origin ${RELEASE_BRANCH}`;
	await ensureReleasePullRequest();

	console.log("[release] Version PR ready");
}

try {
	await main();
} catch (error) {
	console.error("[release] Versioning failed");

	console.error(error instanceof Error ? (error.stack ?? error.message) : error);

	process.exitCode = 1;
}
